-- MySQL Script generated by MySQL Workbench
-- Mon May  5 10:55:47 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customers` (
  `id_customers` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `city` VARCHAR(65) NULL,
  `street` VARCHAR(65) NULL,
  `country` VARCHAR(70) NULL,
  `postal_code` VARCHAR(10) NULL,
  PRIMARY KEY (`id_customers`),
  UNIQUE INDEX `id_customers_UNIQUE` (`id_customers` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tables`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tables` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tables` (
  `id_tables` INT NOT NULL AUTO_INCREMENT,
  `seats` INT NOT NULL,
  `number` INT NOT NULL,
  PRIMARY KEY (`id_tables`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE,
  UNIQUE INDEX `id_tables_UNIQUE` (`id_tables` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Rooms` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Rooms` (
  `id_rooms` INT NOT NULL AUTO_INCREMENT,
  `number` INT NOT NULL,
  `capacity` INT NOT NULL,
  PRIMARY KEY (`id_rooms`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE,
  UNIQUE INDEX `id_rooms_UNIQUE` (`id_rooms` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reservations` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reservations` (
  `id_reservations` INT NOT NULL AUTO_INCREMENT,
  `date_start` DATE NOT NULL,
  `time` TIME NULL,
  `date_end` DATE NOT NULL,
  `Customers_Fk` INT NOT NULL,
  `Tables_Fk` INT NOT NULL,
  `Rooms_Fk` INT NOT NULL,
  PRIMARY KEY (`id_reservations`),
  UNIQUE INDEX `idReservations_UNIQUE` (`id_reservations` ASC) VISIBLE,
  INDEX `fk_Reservations_Customers1_idx` (`Customers_Fk` ASC) VISIBLE,
  INDEX `fk_Reservations_Tables1_idx` (`Tables_Fk` ASC) VISIBLE,
  INDEX `fk_Reservations_Rooms1_idx` (`Rooms_Fk` ASC) VISIBLE,
  CONSTRAINT `fk_Reservations_Customers1`
    FOREIGN KEY (`Customers_Fk`)
    REFERENCES `mydb`.`Customers` (`id_customers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservations_Tables1`
    FOREIGN KEY (`Tables_Fk`)
    REFERENCES `mydb`.`Tables` (`id_tables`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservations_Rooms1`
    FOREIGN KEY (`Rooms_Fk`)
    REFERENCES `mydb`.`Rooms` (`id_rooms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MESSAGES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MESSAGES` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MESSAGES` (
  `id_messages` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `message` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id_messages`),
  UNIQUE INDEX `id_messages_UNIQUE` (`id_messages` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO Tables (seats, number) VALUES
  (2, 101),
  (4, 102),
  (6, 103),
  (2, 104),
  (4, 105),
  (6, 106),
  (2, 107),
  (4, 108),
  (6, 109),
  (2, 110);

INSERT INTO Rooms (number, capacity) VALUES
  (201, 1),
  (202, 2),
  (203, 3),
  (204, 4),
  (205, 5),
  (206, 6),
  (207, 2),
  (208, 3),
  (209, 4),
  (210, 5);